--!strict

export type PlayerStats = {
	MaxHealth: number,
	DamageMultiplier: number,
	Armor: number,
	Speed: number,
	JumpHeight: number,
	AttackingSpeedDifference: number,
	AttackingJumpHeightDifference: number,
	BlockingSpeedDifference: number,
	BlockingJumpHeightDifference: number,
	HealthRegenRate: number,
	MaxStamina: number,
	StaminaRegenRate: number,
	StaminaDrainRate: number,
	SprintSpeedDifference: number,
	SprintRegenDelay: number,
	StunnedSpeedDifferenceMultiplier: number,
}

return {}
